import streamlit as st
import openai
openai.api_key = st.secrets["OPENAI_KEY"]

def openai_image(prompt):
    response = openai.Image.create(
      prompt=prompt,
      n=1,
      size="256x256"
    )
    image_url = response['data'][0]['url']
    return image_url

def run():
    st.set_page_config(
      page_title="OpenAI",
      page_icon="✨"
    )
    st.title("Generate your own image!")

    # Split page into 2 columns
    col1, col2 = st.columns([3, 5])

    # Column 2 will contain our choices
    image_style = col2.selectbox('Choose your image style',["A photo of a ","An oil painting of a "])
    animal = col2.selectbox('Choose your animal',["fuzzy panda ","British shorthair cat ","Persian cat ","Shiba Inu dog ","raccoon "])
    hat = col2.selectbox('Choose the type of hat',["wearing a cowboy hat and ","wearing a fedora ","wearing a motorcycle helmet and "])
    clothing = col2.selectbox('Choose your outfit',["red shirt ","black leather jacket "])
    activity = col2.selectbox('Choose your activity',["playing a guitar ","skateboarding ", "riding a bike "])
    location = col2.selectbox('Choose your location',["in a garden.","on a beach.","on top of a mountain."])

    prompt = image_style + animal + hat + clothing + activity + location
    st.write("Your choice is: " + prompt)
    image_button = st.button("Generate image!")

    if image_button:
        with col1:
          with st.spinner("Loading..."):
            image_url = openai_image(prompt)
            st.image(image_url, caption="Generated by OpenAI")
            
if __name__ == "__main__":
    run()
