import streamlit as st
import openai
from PIL import Image
openai.api_key = st.secrets["OPENAI_KEY"]
import os

def openai_image_variation(fpath):
    response = openai.Image.create_variation(
        image=open(fpath, "rb"),
        n=1,
        size="1024x1024"
        )

    image_url = response['data'][0]['url']
    return image_url

def run():
    picture = st.camera_input("Take a picture")

    if picture:
        # will capture and save the input so that pillow can make changes to it
        # camera input saves as a PNG file
        im = Image.open(picture)

        curr_width, curr_height = im.size
        new_size = [min(im.size), min(im.size)]
        width_diff = (curr_width-new_size[0])/2
        height_diff = (curr_height-new_size[1])/2

        left = width_diff
        top = height_diff
        right = curr_width - width_diff
        bottom = curr_height - height_diff

        im = im.crop((left, top, right, bottom))

        try:
            os.remove("temp.png")
        except FileNotFoundError:
            pass

        try:
            im.save("temp.png")
        except IOError:
            print("Error! Cannot create file.")
            
        col1, col2 = st.columns(2)
        with col1:
            st.image("temp.png", caption="Before")

        with col2:
         with st.spinner("Loading..."):
           image_url = openai_image_variation("temp.png")
           st.image(image_url, caption="Generated by OpenAI")
if __name__ == "__main__":
    run()
